spring.datasource.url: jdbc:mysql://localhost:3306/club
spring.datasource.username: club_usr
spring.datasource.password: passwd

spring:
  jpa:
    properties:
      jakarta:
        persistence:
          schema-generation:
            database:
              action: drop-and-create