spring:
  datasource:
    url: jdbc:mysql://localhost:3306/club
    username: club_usr
    password: passwd
  jpa:
    properties:
      jakarta:
        persistence:
          schema-generation:
            database:
              action: none
