spring.datasource.url : jdbc:derby://localhost:1527/club
spring.datasource.username: club_usr
spring.datasource.password: passwd

spring.jpa.properties.jakarta.persistence.schema-generation.database.action: drop-and-create
