spring.datasource.url: jdbc:h2:mem:club;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1

spring:
  datasource:
    username: club_usr
    password: passwd
  jpa:
    properties:
      jakarta:
        persistence:
          schema-generation:
            database:
              action: drop-and-create
    show-sql: true
